name: PR-Validations

on:
  pull_request:

jobs:
  PR-Validations:
    runs-on: ubuntu-latest

    container:
      image: gcr.io/cloud-marketplace/google/bazel:latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Bazel Test
        run: |
          bazel test //...
